[package]
name = "bog"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.0.0-rc.1"

[dev-dependencies]
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
